// Pre-loaded sample palettes.
// Edit descriptions, colors, and positions freely.
// Audio files are served from public/audio/.

const samplePalettes = [
  {
    id: 'sample-water',
    name: 'Creek and Sky',
    date: 'Sample',
    nodes: [
      {
        id: 'sw-1',
        text: 'The sound of Mill Creek moving over rocks',
        color: '#3b82f6',
        audioUrl: '/audio/mill-creek-water.wav',
        fileName: 'mill-creek-water.wav',
        x: 22, y: 35,
        date: 'Sample',
      },
      {
        id: 'sw-2',
        text: 'Wind through the trees along the creek',
        color: '#6ee7b7',
        audioUrl: '/audio/mill-creek-wind.m4a',
        fileName: 'mill-creek-wind.m4a',
        x: 40, y: 60,
        date: 'Sample',
      },
      {
        id: 'sw-3',
        text: 'A waterfall, somewhere not too far away',
        color: '#1d4ed8',
        audioUrl: '/audio/waterfall.WAV',
        fileName: 'waterfall.WAV',
        x: 12, y: 75,
        date: 'Sample',
      },
      {
        id: 'sw-4',
        text: 'Water and sky — altitude makes everything feel distant',
        color: '#7dd3fc',
        audioUrl: '/audio/airplane-water.WAV',
        fileName: 'airplane-water.WAV',
        x: 62, y: 22,
        date: 'Sample',
      },
      {
        id: 'sw-5',
        text: 'Wings and water — a very Whitman sound',
        color: '#34d399',
        audioUrl: '/audio/quacking-wings-flapping.WAV',
        fileName: 'quacking-wings-flapping.WAV',
        x: 33, y: 48,
        date: 'Sample',
      },
    ],
  },
  {
    id: 'sample-campus',
    name: 'Campus',
    date: 'Sample',
    nodes: [
      {
        id: 'sc-1',
        text: 'Footsteps across the quad on an ordinary afternoon',
        color: '#fbbf24',
        audioUrl: '/audio/walking-across-campus.m4a',
        fileName: 'walking-across-campus.m4a',
        x: 55, y: 62,
        date: 'Sample',
      },
      {
        id: 'sc-2',
        text: 'A plane passing overhead — going somewhere else',
        color: '#94a3b8',
        audioUrl: '/audio/plane-overhead_mixdown.wav',
        fileName: 'plane-overhead_mixdown.wav',
        x: 78, y: 18,
        date: 'Sample',
      },
      {
        id: 'sc-3',
        text: 'Jazz spilling out of a conference room',
        color: '#c084fc',
        audioUrl: '/audio/whitman-undergraduate-conference-jazz.m4a',
        fileName: 'whitman-undergraduate-conference-jazz.m4a',
        x: 68, y: 50,
        date: 'Sample',
      },
      {
        id: 'sc-4',
        text: 'Something dripping in Olin — has it always done that?',
        color: '#38bdf8',
        audioUrl: '/audio/olin-leak.wav',
        fileName: 'olin-leak.wav',
        x: 42, y: 35,
        date: 'Sample',
      },
      {
        id: 'sc-5',
        text: 'Groundskeeping — the campus tending to itself',
        color: '#a3e635',
        audioUrl: '/audio/leaf-blower.WAV',
        fileName: 'leaf-blower.WAV',
        x: 20, y: 52,
        date: 'Sample',
      },
      {
        id: 'sc-6',
        text: 'Chalk and thought, scratched into a surface',
        color: '#6366f1',
        audioUrl: '/audio/blackboard-writing.wav',
        fileName: 'blackboard-writing.wav',
        x: 85, y: 32,
        date: 'Sample',
      },
      {
        id: 'sc-7',
        text: 'The ducks of Lakum Dukum — very much at home',
        color: '#fb923c',
        audioUrl: '/audio/lakum-duckum.m4a',
        fileName: 'lakum-duckum.m4a',
        x: 58, y: 80,
        date: 'Sample',
      },
    ],
  },
  {
    id: 'sample-domestic',
    name: 'Domestic',
    date: 'Sample',
    nodes: [
      {
        id: 'sd-1',
        text: 'The kettle building toward a boil',
        color: '#ef4444',
        audioUrl: '/audio/electric-kettle-boiling.m4a',
        fileName: 'electric-kettle-boiling.m4a',
        x: 25, y: 28,
        date: 'Sample',
      },
      {
        id: 'sd-2',
        text: 'A hair dryer in a small bathroom',
        color: '#f59e0b',
        audioUrl: '/audio/hair-dryer.m4a',
        fileName: 'hair-dryer.m4a',
        x: 62, y: 38,
        date: 'Sample',
      },
      {
        id: 'sd-3',
        text: 'Morning ritual — water, brush, repeat',
        color: '#06b6d4',
        audioUrl: '/audio/faucet-brushing-teeth.m4a',
        fileName: 'faucet-brushing-teeth.m4a',
        x: 42, y: 68,
        date: 'Sample',
      },
      {
        id: 'sd-4',
        text: 'A pencil sharpener doing its one job',
        color: '#84cc16',
        audioUrl: '/audio/pencil-sharpener.m4a',
        fileName: 'pencil-sharpener.m4a',
        x: 80, y: 75,
        date: 'Sample',
      },
      {
        id: 'sd-5',
        text: 'A small involuntary sound — the body interrupting itself',
        color: '#ec4899',
        audioUrl: '/audio/hiccup.wav',
        fileName: 'hiccup.wav',
        x: 55, y: 20,
        date: 'Sample',
      },
      {
        id: 'sd-6',
        text: 'A duck, somewhere it probably should not be',
        color: '#a78bfa',
        audioUrl: '/audio/lakum-dukum-2.m4a',
        fileName: 'lakum-dukum-2.m4a',
        x: 38, y: 45,
        date: 'Sample',
      },
    ],
  },
  {
    id: 'sample-strange',
    name: 'Strange Signals',
    date: 'Sample',
    nodes: [
      {
        id: 'ss-1',
        text: 'A voice insisting on something',
        color: '#f43f5e',
        audioUrl: '/audio/wait-wait-wait.m4a',
        fileName: 'wait-wait-wait.m4a',
        x: 35, y: 40,
        date: 'Sample',
      },
      {
        id: 'ss-2',
        text: 'A warning that is also a color',
        color: '#eab308',
        audioUrl: '/audio/yellow-lights-are-flashing.m4a',
        fileName: 'yellow-lights-are-flashing.m4a',
        x: 70, y: 65,
        date: 'Sample',
      },
      {
        id: 'ss-3',
        text: 'Something between a crowd and a herd',
        color: '#8b5cf6',
        audioUrl: '/audio/balloon-stampede.m4a',
        fileName: 'balloon-stampede.m4a',
        x: 20, y: 78,
        date: 'Sample',
      },
      {
        id: 'ss-4',
        text: 'Animals at rest — or possibly not resting at all',
        color: '#4ade80',
        audioUrl: '/audio/at-graze.m4a',
        fileName: 'at-graze.m4a',
        x: 55, y: 25,
        date: 'Sample',
      },
      {
        id: 'ss-5',
        text: 'Wings and water, out of context',
        color: '#f0abfc',
        audioUrl: '/audio/quacking-wings-flapping.WAV',
        fileName: 'quacking-wings-flapping.WAV',
        x: 48, y: 55,
        date: 'Sample',
      },
    ],
  },
  {
    id: 'sample-trio',
    name: 'Trio',
    date: 'Sample',
    nodes: [
      {
        id: 'st-1',
        text: 'A bell in a tree at Wallula Gap',
        color: '#dc2626',
        audioUrl: '/audio/wallula-gap-tree-bell.m4a',
        fileName: 'wallula-gap-tree-bell.m4a',
        x: 15, y: 22,
        date: 'Sample',
      },
      {
        id: 'st-2',
        text: 'Twelve seconds of breathing',
        color: '#0d9488',
        audioUrl: '/audio/it-takes-12-secs-to-breathe.m4a',
        fileName: 'it-takes-12-secs-to-breathe.m4a',
        x: 78, y: 72,
        date: 'Sample',
      },
      {
        id: 'st-3',
        text: 'A swing that needs oiling',
        color: '#d97706',
        audioUrl: '/audio/squeaky-swing.m4a',
        fileName: 'squeaky-swing.m4a',
        x: 68, y: 22,
        date: 'Sample',
      },
    ],
  },
];

export default samplePalettes;
