// Pre-loaded sample palettes.
// Edit descriptions, colors, and positions freely.
// Audio files are served from public/audio/.

const samplePalettes = [

{
  "id": 2364,
  "name": "Sounds of DIS 2026, Part 1",
  "date": "6/15/2026",
  "nodes": [
    {
      "id": "1781547082231",
      "text": "How long does it take to walk from Terminal 2 to Terminal 3?",
      "color": "#d278d9",
      "audioUrl": "/audio/DIS26_Walking_to_G_gates.m4a",
      "fileName": "DIS26: Through the SFO Airport",
      "x": 82,
      "y": 33,
      "date": "6/15/2026"
    },
    {
      "id": "1781547132163",
      "text": "And the crowd breaks into applause...",
      "color": "#16c8d4",
      "audioUrl": "/audio/DIS26_Clapping.m4a",
      "fileName": "DIS26: Clapping",
      "x": 51,
      "y": 54,
      "date": "6/15/2026"
    },
    {
      "id": "1781547170663",
      "text": "How long would you wait in line to get some ice cream?",
      "color": "#ebc60f",
      "audioUrl": "/audio/DIS26_Ice_cream_lid.m4a",
      "fileName": "DIS26: Ice Cream",
      "x": 13,
      "y": 50,
      "date": "6/15/2026"
    },
    {
      "id": "1781547238531",
      "text": "The birds sound tropical.",
      "color": "#71f4c8",
      "audioUrl": "/audio/DIS26_Some_Birds.m4a",
      "fileName": "DIS26: Birds in the Trees",
      "x": 44,
      "y": 30,
      "date": "6/15/2026"
    },
    {
      "id": "1781547298340",
      "text": "Descending",
      "color": "#8321d4",
      "audioUrl": "/audio/DIS26_Stairs.m4a",
      "fileName": "DIS26: Walking Down the Stairs",
      "x": 75,
      "y": 12,
      "date": "6/15/2026"
    }
  ]
},

  {
    id: 'sample-water',
    name: 'Water in many forms',
    date: 'May 15, 2026',
    nodes: [
      {
        id: 'sw-1',
        text: 'The sound of Mill Creek moving over rocks',
        color: '#3b82f6',
        audioUrl: '/audio/mill-creek-water.wav',
        fileName: 'mill-creek-water.wav',
        x: 22, y: 35,
        date: 'unknown',
      },
      {
        id: 'sw-2',
        text: 'Wind through the trees along Mill Creek',
        color: '#6ee7b7',
        audioUrl: '/audio/mill-creek-wind.m4a',
        fileName: 'mill-creek-wind.m4a',
        x: 40, y: 60,
        date: 'November 5, 2025',
      },
      {
        id: 'sw-3',
        text: 'A fountain? A waterfall? It is somewhere on campus...',
        color: '#1d4ed8',
        audioUrl: '/audio/waterfall.WAV',
        fileName: 'waterfall.WAV',
        x: 12, y: 75,
        date: 'October 7, 2025',
      },
      {
        id: 'sw-4',
        text: 'Water below and an airplane above',
        color: '#7dd3fc',
        audioUrl: '/audio/airplane-water.WAV',
        fileName: 'airplane-water.WAV',
        x: 62, y: 22,
        date: 'October 7, 2025',
      },
      {
        id: 'sw-5',
        text: 'The ducks, doing their thing...',
        color: '#34d399',
        audioUrl: '/audio/quacking-wings-flapping.WAV',
        fileName: 'quacking-wings-flapping.WAV',
        x: 33, y: 48,
        date: 'October 7, 2025',
      },
    ],
  },
  {
    id: 'sample-campus',
    name: 'Around Campus',
    date: 'May 15, 2026',
    nodes: [
      {
        id: 'sc-1',
        text: 'Walking across campus, quickly, on an ordinary afternoon',
        color: '#fbbf24',
        audioUrl: '/audio/walking-across-campus.m4a',
        fileName: 'walking-across-campus.m4a',
        x: 55, y: 62,
        date: 'November 7, 2025',
      },
      {
        id: 'sc-2',
        text: 'A plane passing overhead',
        color: '#94a3b8',
        audioUrl: '/audio/plane-overhead_mixdown.wav',
        fileName: 'plane-overhead_mixdown.wav',
        x: 78, y: 18,
        date: 'Unknown',
      },
      {
        id: 'sc-3',
        text: 'Jazz performance at lunch during the Whitman Undergraduate Conference, with lots of chatter',
        color: '#c084fc',
        audioUrl: '/audio/whitman-undergraduate-conference-jazz.m4a',
        fileName: 'whitman-undergraduate-conference-jazz.m4a',
        x: 68, y: 50,
        date: 'April 14, 2026',
      },
      {
        id: 'sc-4',
        text: 'Water dripping from the ceiling in the CS Commons, eep!',
        color: '#38bdf8',
        audioUrl: '/audio/olin-leak.wav',
        fileName: 'olin-leak.wav',
        x: 42, y: 35,
        date: 'April 22, 2026',
      },
      {
        id: 'sc-5',
        text: 'We always had a lawnmower during our sound class, kind of ironic',
        color: '#a3e635',
        audioUrl: '/audio/leaf-blower.WAV',
        fileName: 'leaf-blower.WAV',
        x: 20, y: 52,
        date: 'October 7, 2025',
      },
      {
        id: 'sc-6',
        text: 'Chalk and thought, scratched into a surface',
        color: '#6366f1',
        audioUrl: '/audio/blackboard-writing.wav',
        fileName: 'blackboard-writing.wav',
        x: 85, y: 32,
        date: 'Unknown',
      },
      {
        id: 'sc-7',
        text: 'The ducks of Lakum Dukum, very much at home',
        color: '#fb923c',
        audioUrl: '/audio/lakum-duckum.m4a',
        fileName: 'lakum-duckum.m4a',
        x: 58, y: 80,
        date: 'November 5, 2025',
      },
    ],
  },
  {
    id: 'sample-domestic',
    name: 'Everyday Life',
    date: 'May 15, 2026',
    nodes: [
      {
        id: 'sd-1',
        text: 'An electric kettle building toward a boil',
        color: '#ef4444',
        audioUrl: '/audio/electric-kettle-boiling.m4a',
        fileName: 'electric-kettle-boiling.m4a',
        x: 25, y: 28,
        date: 'November 7, 2025',
      },
      {
        id: 'sd-2',
        text: 'A hair dryer',
        color: '#f59e0b',
        audioUrl: '/audio/hair-dryer.m4a',
        fileName: 'hair-dryer.m4a',
        x: 62, y: 38,
        date: 'November 5, 2025',
      },
      {
        id: 'sd-3',
        text: 'Brushing teeth and faucet running in the morning',
        color: '#06b6d4',
        audioUrl: '/audio/faucet-brushing-teeth.m4a',
        fileName: 'faucet-brushing-teeth.m4a',
        x: 42, y: 68,
        date: 'November 5, 2025',
      },
      {
        id: 'sd-4',
        text: 'A pencil sharpener doing its one job',
        color: '#84cc16',
        audioUrl: '/audio/pencil-sharpener.m4a',
        fileName: 'pencil-sharpener.m4a',
        x: 80, y: 75,
        date: 'November 5, 2025',
      },
      {
        id: 'sd-5',
        text: 'Hiccup! Hiccup!',
        color: '#ec4899',
        audioUrl: '/audio/hiccup.wav',
        fileName: 'hiccup.wav',
        x: 55, y: 20,
        date: 'Unknown',
      },
      {
        id: 'sd-6',
        text: 'A duck, where it feels at home',
        color: '#a78bfa',
        audioUrl: '/audio/lakum-dukum-2.m4a',
        fileName: 'lakum-dukum-2.m4a',
        x: 38, y: 45,
        date: 'Sample',
      },
    ],
  },
  {
    id: 'sample-strange',
    name: 'Disparate Signals',
    date: 'May 15, 2026',
    nodes: [
      {
        id: 'ss-1',
        text: 'Not time to cross the street yet...',
        color: '#f43f5e',
        audioUrl: '/audio/wait-wait-wait.m4a',
        fileName: 'wait-wait-wait.m4a',
        x: 35, y: 40,
        date: 'Sample',
      },
      {
        id: 'ss-2',
        text: 'Now you can go, because yellow lights are flashing',
        color: '#eab308',
        audioUrl: '/audio/yellow-lights-are-flashing.m4a',
        fileName: 'yellow-lights-are-flashing.m4a',
        x: 70, y: 65,
        date: 'Sample',
      },
      {
        id: 'ss-3',
        text: 'Walla Walla in Spring: Where two dozen hot air balloons might pass right over your house at sunset',
        color: '#8b5cf6',
        audioUrl: '/audio/balloon-stampede.m4a',
        fileName: 'balloon-stampede.m4a',
        x: 20, y: 78,
        date: 'Sample',
      },
      {
        id: 'ss-4',
        text: 'The ambience of Graze',
        color: '#4ade80',
        audioUrl: '/audio/at-graze.m4a',
        fileName: 'at-graze.m4a',
        x: 55, y: 25,
        date: 'Sample',
      },
      {
        id: 'ss-5',
        text: 'Quacking and flapping and splashing',
        color: '#f0abfc',
        audioUrl: '/audio/quacking-wings-flapping.WAV',
        fileName: 'quacking-wings-flapping.WAV',
        x: 48, y: 55,
        date: 'Sample',
      },
    ],
  },
  {
    id: 'sample-trio',
    name: 'Three unrelated sounds',
    date: 'May 15, 2026',
    nodes: [
      {
        id: 'st-1',
        text: 'A bell in a lonely tree at Wallula Gap',
        color: '#dc2626',
        audioUrl: '/audio/wallula-gap-tree-bell.m4a',
        fileName: 'wallula-gap-tree-bell.m4a',
        x: 15, y: 22,
        date: 'Sample',
      },
      {
        id: 'st-2',
        text: 'It takes 12 seconds to breathe',
        color: '#0d9488',
        audioUrl: '/audio/it-takes-12-secs-to-breathe.m4a',
        fileName: 'it-takes-12-secs-to-breathe.m4a',
        x: 78, y: 72,
        date: 'Sample',
      },
      {
        id: 'st-3',
        text: 'A swing that has a lot to say',
        color: '#d97706',
        audioUrl: '/audio/squeaky-swing.m4a',
        fileName: 'squeaky-swing.m4a',
        x: 68, y: 22,
        date: 'Sample',
      },
    ],
  },
];

export default samplePalettes;
