// Manifest of available sounds in public/audio/.
// Add new sounds by dropping files into public/audio/ and adding an entry here.
// displayName is what participants see in the sound picker.

const SOUND_LIBRARY = [
  { fileName: 'airplane-water.WAV',                       displayName: 'Airplane Water' },
  { fileName: 'at-graze.m4a',                             displayName: 'At Graze' },
  { fileName: 'balloon-stampede.m4a',                     displayName: 'Balloon Stampede' },
  { fileName: 'blackboard-writing.wav',                   displayName: 'Blackboard Writing' },
  { fileName: 'blackboard-writing.wav',                   displayName: 'Blackboard Writing' },
  { fileName: 'Bubbles and foot spa.m4a',              displayName: 'Bubbling Foot Spa' },
  { fileName: 'DIS26_SarahPink1.m4a',              displayName: 'DIS26: Sarah Pink 1' },
  { fileName: 'DIS26_SarahPink2.m4a',              displayName: 'DIS26: Sarah Pink 2' },
  { fileName: 'DIS26_Clapping.m4a',              displayName: 'DIS26: Clapping' },
  { fileName: 'DIS26_Coffee_Break1.m4a',              displayName: 'DIS26: Chatter at Coffee Break' },
  { fileName: 'DIS26_Toilet_flush.m4a',              displayName: 'DIS26: Toilet Flushing' },
  { fileName: 'DIS26_Some_Birds.m4a',              displayName: 'DIS26: Birds in the Trees' },
  { fileName: 'DIS26_Stairs.m4a',              displayName: 'DIS26: Walking Down the Stairs' },
  { fileName: 'DIS26_Unknown_whirr.m4a',              displayName: 'DIS26: What is that Whirr' },
  { fileName: 'DIS26_Ice_cream_lid.m4a',              displayName: 'DIS26: Ice Cream' },
  { fileName: 'DIS26_festival_music1.mp3',              displayName: 'DIS26: Music at a Festival, 1' },
  { fileName: 'DIS26_festival_music2.mp3',              displayName: 'DIS26: Music at a Festival, 2' },
  { fileName: 'DIS26_Walking_to_G_gates.m4a',              displayName: 'DIS26: Through the SFO Airport' },
  { fileName: 'DIS26_fan_heaven.m4a',              displayName: 'DIS26: Glorious Fan' },
  { fileName: 'faucet-brushing-teeth.m4a',                displayName: 'Faucet / Brushing Teeth' },
  { fileName: 'hair-dryer.m4a',                           displayName: 'Hair Dryer' },
  { fileName: 'hiccup.wav',                               displayName: 'Hiccup' },
  { fileName: 'it-takes-12-secs-to-breathe.m4a',         displayName: 'It Takes 12 Seconds to Breathe' },
  { fileName: 'lakum-duckum.m4a',                         displayName: 'Lakum Duckum' },
  { fileName: 'lakum-dukum-2.m4a',                        displayName: 'Lakum Dukum 2' },
  { fileName: 'leaf-blower.WAV',                          displayName: 'Leaf Blower' },
  { fileName: 'mill-creek-water.wav',                     displayName: 'Mill Creek Water' },
  { fileName: 'mill-creek-wind.m4a',                      displayName: 'Mill Creek Wind' },
  { fileName: 'olin-leak.wav',                            displayName: 'Olin Leak' },
  { fileName: 'pencil-sharpener.m4a',                     displayName: 'Pencil Sharpener' },
  { fileName: 'plane-overhead_mixdown.wav',               displayName: 'Plane Overhead' },
  { fileName: 'plane-to-whitman.m4a',                     displayName: 'Plane to Whitman' },
  { fileName: 'putting-a-phone-underwater-by-maxey.m4a',  displayName: 'Phone Underwater (by Maxey)' },
  { fileName: 'quacking-wings-flapping.WAV',              displayName: 'Quacking / Wings Flapping' },
  { fileName: 'squeaky-swing.m4a',                        displayName: 'Squeaky Swing' },
  { fileName: 'wait-wait-wait.m4a',                       displayName: 'Wait Wait Wait' },
  { fileName: 'walking-across-campus.m4a',                displayName: 'Walking Across Campus' },
  { fileName: 'wallula-gap-tree-bell.m4a',                displayName: 'Wallula Gap Tree Bell' },
  { fileName: 'waterfall.WAV',                            displayName: 'Waterfall' },
  { fileName: 'watermelon.m4a',                           displayName: 'Watermelon' },
  { fileName: 'whitman-undergraduate-conference-jazz.m4a',displayName: 'Whitman Conference Jazz' },
  { fileName: 'yellow-lights-are-flashing.m4a',           displayName: 'Yellow Lights Are Flashing' },
].map(s => ({ ...s, audioUrl: `/audio/${s.fileName}` }));

export default SOUND_LIBRARY;
